In [18]:
import re
import pandas as pd

In [19]:
f = open('WhatsApp Chat with Deepanshu.txt', 'r', encoding='utf-8')

In [20]:
data = f.read()

In [21]:
print(data)

15/08/2025, 9:56 am - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.
21/08/2025, 1:38 pm - Deepanshu: Tera wifi sahi hua
21/08/2025, 1:52 pm - Hariom Nagar: nahi par vo anil ko bola hai to 10 din ki bol raha hai
21/08/2025, 1:52 pm - Deepanshu: Last semester se bol raha hai yeh toh
21/08/2025, 1:52 pm - Hariom Nagar: hnn abhi grp me num aaya hai uspe call krke boluga
21/08/2025, 1:53 pm - Deepanshu: Bol bhai
21/08/2025, 1:53 pm - Hariom Nagar: hnn
22/08/2025, 4:29 pm - Hariom Nagar: clg kab aa raha hai
22/08/2025, 4:29 pm - Deepanshu: Monday ko
22/08/2025, 4:29 pm - Deepanshu: Kya hua ?
22/08/2025, 4:30 pm - Hariom Nagar: kich nahi bas aesi.
22/08/2025, 4:30 pm - Deepanshu: Monday shaym tak aa jau ga
24/08/2025, 11:30 am - Hariom Nagar: TAP ka form bhara hai tune
24/08/2025, 11:30 am - Deepanshu: Nahi
24/08/2025, 11:30 am - Deepanshu: Tune?
24/08/2025, 11:30 am - Hariom Nagar: na
24/08/2025, 11:31 am - Hariom Nagar: kyu nahi bhara?
24/08/2025, 11:31 am - Deepanshu: Kuch fayda nahi hai
24/08/2025, 11:31 am - Deepanshu: Mene discuss Kiya abhi jo member hai unke sath
24/08/2025, 11:31 am - Hariom Nagar: bharat to placmet hone ke chanse bad jate
24/08/2025, 11:32 am - Deepanshu: Nahi same haal hai andar ka bhi
25/08/2025, 7:52 pm - Deepanshu: GitHub https://share.google/8kwdTYzHQBxgy65Tw
26/08/2025, 8:35 am - Hariom Nagar: class aa ja, lab hai aaj
26/08/2025, 8:41 am - Deepanshu: Bsdk bus mei hu mai
26/08/2025, 8:41 am - Deepanshu: Tu class aa ja
26/08/2025, 5:28 pm - Hariom Nagar: mess chalte hai lift me aaja
26/08/2025, 11:20 pm - Hariom Nagar:
27/08/2025, 10:00 am - Deepanshu: Proxy mar de
27/08/2025, 10:00 am - Deepanshu: Bhai plz
27/08/2025, 10:01 am - Hariom Nagar: apni dono ke Roll num to side by side hai kaise bro
27/08/2025, 10:01 am - Deepanshu: Kisi aas pas wale se bol de
27/08/2025, 10:02 am - Hariom Nagar: thi hai me aagman ko bolta hu
28/08/2025, 6:55 pm - Hariom Nagar: reg form chaiye kya?
28/08/2025, 6:55 pm - Deepanshu: nahi hai mere pass
29/08/2025, 8:35 am - Hariom Nagar: class jayga aaj
29/08/2025, 8:44 am - Deepanshu: Nahi
29/08/2025, 10:48 pm - Deepanshu: from fastapi import FastAPI, HTTPException, BackgroundTasks, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, validator
from typing import Dict, List, Optional, Tuple, Any
from datetime import datetime
from enum import Enum
import re
import json
import logging
import uuid
import asyncio
from contextlib import asynccontextmanager

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class ExpenseCategory(str, Enum):
    FOOD = "Food"
    TRAVEL = "Travel"
    SHOPPING = "Shopping"
    UTILITIES = "Utilities"
    ENTERTAINMENT = "Entertainment"
    HEALTHCARE = "Healthcare"
    FUEL = "Fuel"
    OTHER = "Other"

class DataSource(str, Enum):
    SMS = "SMS"
    EMAIL = "Email"
    NOTIFICATION = "Notification"
    RECEIPT = "Receipt"
    BANK_STATEMENT = "Bank Statement"

class ProcessingStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

# Pydantic Models for API
class ExpenseEntryResponse(BaseModel):
    id: str
    amount: float
    category: ExpenseCategory
    description: str
    merchant: str
    timestamp: datetime
    source: DataSource
    confidence_score: float
    raw_text: str

class SMSProcessRequest(BaseModel):
    sms_content: str
    sender: Optional[str] = None
    received_at: Optional[datetime] = None

class EmailProcessRequest(BaseModel):
    email_content: str
    subject: str
    sender: Optional[str] = None
    received_at: Optional[datetime] = None

class ReceiptProcessRequest(BaseModel):
    receipt_text: str
    merchant_name: Optional[str] = None
    amount: Optional[float] = None
    timestamp: Optional[datetime] = None

class FeedbackRequest(BaseModel):
    expense_id: str
    correct_category: ExpenseCategory
    user_notes: Optional[str] = None

class BulkProcessRequest(BaseModel):
    data_sources: List[Dict[str, Any]]

    @validator('data_sources')
    def validate_data_sources(cls, v):
        required_fields = ['type', 'content']
        for item in v:
            if not all(field in item for field in required_fields):
                raise ValueError('Each data source must have type and content fields')
            if item['type'] not in [source.value for source in DataSource]:
                raise ValueError(f'Invalid source type: {item["type"]}')
        return v

class ExpenseSummaryResponse(BaseModel):
    total_expenses: int
    total_amount: float
    category_breakdown: Dict[str, Dict[str, float]]
    performance_metrics: Dict[str, Any]
    top_merchants: List[Dict[str, Any]]
    date_range: Dict[str, datetime]

class ProcessingTaskResponse(BaseModel):
    task_id: str
    status: ProcessingStatus
    message: str
    created_at: datetime
    result: Optional[Dict[str, Any]] = None

# Core Classes
class ExpenseEntry:
    def __init__(self, amount: float, category: ExpenseCategory, description: str,
                 merchant: str, timestamp: datetime, source: DataSource,
                 confidence_score: float, raw_text: str):
        self.id = str(uuid.uuid4())
        self.amount = amount
        self.category = category
        self.description = description
        self.merchant = merchant
        self.timestamp = timestamp
        self.source = source
        self.confidence_score = confidence_score
        self.raw_text = raw_text
        self.created_at = datetime.now()

    def to_dict(self) -> Dict[str, Any]:
        return {
            'id': self.id,
            'amount': self.amount,
            'category': self.category.value,
            'description': self.description,
            'merchant': self.merchant,
            'timestamp': self.timestamp.isoformat(),
            'source': self.source.value,
            'confidence_score': self.confidence_score,
            'raw_text': self.raw_text,
            'created_at': self.created_at.isoformat()
        }

class DataProcessor:
    """Enhanced Data Processing Layer with async support"""

    def __init__(self):
        self.sms_patterns = {
            'debit': r'(?:debited|charged|spent|paid)\s*(?:rs\.?|inr\.?|₹)?\s*(\d+(?:,\d+)*(?:\.\d{2})?)',
            'merchant': r'(?:at|to|from)\s+([A-Z][A-Z0-9\s]+?)(?:\s+on|\s+dt|\s*\.|$)',
            'card': r'(?:card|a/c)\s*(?:ending\s*)?(?:xx)?(\d{4})',
            'datetime': r'(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{2}:\d{2})'
        }

    async def extract_sms_data(self, sms_text: str, sender: Optional[str] = None) -> Dict[str, Any]:
        """Async SMS data extraction"""
        try:
            sms_text_lower = sms_text.lower()

            # Extract amount
            amount_match = re.search(self.sms_patterns['debit'], sms_text_lower, re.IGNORECASE)
            amount = float(amount_match.group(1).replace(',', '')) if amount_match else 0.0

            # Extract merchant
            merchant_match = re.search(self.sms_patterns['merchant'], sms_text, re.IGNORECASE)
            merchant = merchant_match.group(1).strip() if merchant_match else (sender or "Unknown")

            # Extract datetime (simplified - using current time)
            timestamp = datetime.now()

            logger.info(f"Extracted SMS data: amount={amount}, merchant={merchant}")

            return {
                'amount': amount,
                'merchant': merchant,
                'timestamp': timestamp,
                'description': f"Transaction at {merchant}",
                'raw_text': sms_text
            }
        except Exception as e:
            logger.error(f"Error extracting SMS data: {e}")
            raise HTTPException(status_code=422, detail=f"Failed to process SMS: {str(e)}")

    async def extract_email_data(self, email_content: str, subject: str) -> Dict[str, Any]:
        """Async email data extraction"""
        try:
            # Enhanced email processing patterns
            amount_patterns = [
                r'(?:total|amount|paid|charged)[:$\s]*(?:rs\.?|inr\.?|₹)?\s*(\d+(?:,\d+)*(?:\.\d{2})?)',
                r'₹\s*(\d+(?:,\d+)*(?:\.\d{2})?)',
                r'rs\.?\s*(\d+(?:,\d+)*(?:\.\d{2})?)'
            ]

            amount = 0.0
            for pattern in amount_patterns:
                amount_match = re.search(pattern, email_content, re.IGNORECASE)
                if amount_match:
                    amount = float(amount_match.group(1).replace(',', ''))
                    break

            # Extract merchant from subject
            merchant_keywords = ['from', 'by', '-', '|']
            merchant = subject.split()[0] if subject else "Email Merchant"

            for keyword in merchant_keywords:
                if keyword in subject.lower():
                    merchant = subject.split(keyword)[0].strip()
                    break

            logger.info(f"Extracted email data: amount={amount}, merchant={merchant}")

            return {
                'amount': amount,
                'merchant': merchant,
                'timestamp': datetime.now(),
                'description': subject,
                'raw_text': f"Subject: {subject}\nContent: {email_content[:200]}..."
            }
        except Exception as e:
            logger.error(f"Error extracting email data: {e}")
            raise HTTPException(status_code=422, detail=f"Failed to process email: {str(e)}")

    async def extract_receipt_data(self, receipt_text: str, merchant_name: Optional[str] = None,
                                 amount: Optional[float] = None) -> Dict[str, Any]:
        """Process receipt data"""
        try:
            # If amount not provided, try to extract
            if amount is None:
                amount_pattern = r'(?:total|amount|sum)[:$\s]*(?:rs\.?|inr\.?|₹)?\s*(\d+(?:,\d+)*(?:\.\d{2})?)'
                amount_match = re.search(amount_pattern, receipt_text, re.IGNORECASE)
                amount = float(amount_match.group(1).replace(',', '')) if amount_match else 0.0

            merchant = merchant_name or "Receipt Merchant"

            return {
                'amount': amount,
                'merchant': merchant,
                'timestamp': datetime.now(),
                'description': f"Receipt from {merchant}",
                'raw_text': receipt_text
            }
        except Exception as e:
            logger.error(f"Error extracting receipt data: {e}")
            raise HTTPException(status_code=422, detail=f"Failed to process receipt: {str(e)}")

class IntelligentCategorizer:
    """Enhanced AI Categorizer with async support"""

    def __init__(self):
        self.category_rules = {
            ExpenseCategory.FOOD: ['swiggy', 'zomato', 'uber eats', 'dominos', 'kfc', 'mcdonalds', 'restaurant', 'cafe', 'food', 'pizza', 'burger', 'dining'],
            ExpenseCategory.TRAVEL: ['uber', 'ola', 'metro', 'railway', 'airlines', 'flight', 'bus', 'taxi', 'transport', 'travel', 'booking', 'trip'],
            ExpenseCategory.SHOPPING: ['amazon', 'flipkart', 'myntra', 'big bazaar', 'reliance', 'mall', 'store', 'shopping', 'purchase', 'buy'],
            ExpenseCategory.UTILITIES: ['electricity', 'water', 'gas', 'mobile', 'internet', 'broadband', 'phone', 'utility', 'bill', 'recharge'],
            ExpenseCategory.ENTERTAINMENT: ['movie', 'cinema', 'netflix', 'spotify', 'gaming', 'youtube', 'entertainment', 'streaming', 'subscription'],
            ExpenseCategory.HEALTHCARE: ['pharmacy', 'hospital', 'clinic', 'doctor', 'medical', 'health', 'medicine', 'treatment'],
            ExpenseCategory.FUEL: ['petrol', 'diesel', 'fuel', 'gas station', 'hp', 'bpcl', 'iocl', 'shell', 'pump']
        }
        self.learning_data = []

    async def categorize_expense(self, merchant: str, description: str, amount: float) -> Tuple[ExpenseCategory, float]:
        """Async expense categorization"""
        try:
            text_to_analyze = f"{merchant} {description}".lower()
            category_scores = {}

            for category, keywords in self.category_rules.items():
                score = 0
                for keyword in keywords:
                    if keyword in text_to_analyze:
                        score += 1
                        # Boost score for exact merchant matches
                        if keyword in merchant.lower():
                            score += 2

                if score > 0:
                    category_scores[category] = score / len(keywords)

            # Enhanced fallback logic
            if not category_scores:
                # Amount-based heuristics
                if amount > 5000:
                    return ExpenseCategory.SHOPPING, 0.3
                elif amount > 1000:
                    return ExpenseCategory.OTHER, 0.25
                elif amount < 100:
                    return ExpenseCategory.FOOD, 0.4
                else:
                    return ExpenseCategory.OTHER, 0.2

            # Get best category with scaled confidence
            best_category = max(category_scores.items(), key=lambda x: x[1])
            confidence = min(best_category[1] * 0.8 + 0.2, 0.95)

            logger.info(f"Categorized '{merchant}' as {best_category[0].value} with confidence {confidence:.2f}")

            return best_category[0], confidence

        except Exception as e:
            logger.error(f"Error in categorization: {e}")
            return ExpenseCategory.OTHER, 0.1

    async def learn_from_feedback(self, expense: ExpenseEntry, correct_category: ExpenseCategory):
        """Async feedback learning"""
        try:
            feedback_data = {
                'merchant': expense.merchant,
                'description': expense.description,
                'amount': expense.amount,
                'predicted_category': expense.category,
                'correct_category': correct_category,
                'timestamp': datetime.now()
            }

            self.learning_data.append(feedback_data)
            logger.info(f"Learned from feedback: {expense.merchant} -> {correct_category.value}")

            # Update rules dynamically
            if correct_category not in self.category_rules:
                self.category_rules[correct_category] = []

            merchant_tokens = expense.merchant.lower().split()
            for token in merchant_tokens:
                if len(token) > 2 and token not in self.category_rules[correct_category]:
                    self.category_rules[correct_category].append(token)

        except Exception as e:
            logger.error(f"Error in learning from feedback: {e}")
            raise HTTPException(status_code=500, detail="Failed to process feedback")

class ExpenseAutomationPipeline:
    """Enhanced MLOps Pipeline with async support"""

    def __init__(self):
        self.data_processor = DataProcessor()
        self.categorizer = IntelligentCategorizer()
        self.processed_expenses = {}  # Store by ID
        self.processing_tasks = {}   # Track async tasks
        self.performance_metrics = {
            'total_processed': 0,
            'successful_categorizations': 0,
            'average_confidence': 0.0,
            'error_count': 0
        }

    async def process_expense_source(self, source_type: DataSource, content: str,
                                   additional_data: Dict = None) -> Optional[ExpenseEntry]:
        """Async expense processing"""
        try:
            self.performance_metrics['total_processed'] += 1

            # Data Processing Layer
            if source_type == DataSource.SMS:
                sender = additional_data.get('sender') if additional_data else None
                extracted_data = await self.data_processor.extract_sms_data(content, sender)
            elif source_type == DataSource.EMAIL:
                subject = additional_data.get('subject', '') if additional_data else ''
                extracted_data = await self.data_processor.extract_email_data(content, subject)
            elif source_type == DataSource.RECEIPT:
                merchant_name = additional_data.get('merchant_name') if additional_data else None
                amount = additional_data.get('amount') if additional_data else None
                extracted_data = await self.data_processor.extract_receipt_data(content, merchant_name, amount)
            else:
                # Default processing
                extracted_data = {
                    'amount': additional_data.get('amount', 0.0) if additional_data else 0.0,
                    'merchant': additional_data.get('merchant', 'Unknown') if additional_data else 'Unknown',
                    'timestamp': datetime.now(),
                    'description': content[:100],
                    'raw_text': content
                }

            # Validation
            if extracted_data['amount'] <= 0:
                logger.warning("No valid amount extracted, skipping expense")
                return None

            # AI Categorization
            category, confidence = await self.categorizer.categorize_expense(
                extracted_data['merchant'],
                extracted_data['description'],
                extracted_data['amount']
            )

            # Create expense entry
            expense = ExpenseEntry(
                amount=extracted_data['amount'],
                category=category,
                description=extracted_data['description'],
                merchant=extracted_data['merchant'],
                timestamp=extracted_data['timestamp'],
                source=source_type,
                confidence_score=confidence,
                raw_text=extracted_data['raw_text']
            )

            # Validate and store
            if await self._validate_expense(expense):
                self.processed_expenses[expense.id] = expense
                await self._update_metrics(expense)
                logger.info(f"Successfully processed expense: {expense.merchant} - ₹{expense.amount}")
                return expense
            else:
                logger.warning("Expense failed validation")
                return None

        except Exception as e:
            logger.error(f"Error processing expense: {e}")
            self.performance_metrics['error_count'] += 1
            raise HTTPException(status_code=500, detail=f"Processing failed: {str(e)}")

    async def _validate_expense(self, expense: ExpenseEntry) -> bool:
        """Async expense validation"""
        try:
            # Enhanced validation rules
            if expense.amount <= 0:
                return False
            if expense.amount > 100000:  # Suspicious high amount
                logger.warning(f"High amount detected: ₹{expense.amount}")
            if not expense.merchant or expense.merchant == "Unknown":
                logger.warning("Unknown merchant detected")
            if expense.confidence_score < 0.05:
                logger.warning("Very low confidence score")
                return False

            return True
        except Exception as e:
            logger.error(f"Error in expense validation: {e}")
            return False

    async def _update_metrics(self, expense: ExpenseEntry):
        """Async metrics update"""
        try:
            self.performance_metrics['successful_categorizations'] += 1

            # Calculate running average confidence
            total_successful = self.performance_metrics['successful_categorizations']
            current_avg = self.performance_metrics['average_confidence']
            new_avg = ((current_avg * (total_successful - 1)) + expense.confidence_score) / total_successful
            self.performance_metrics['average_confidence'] = new_avg

        except Exception as e:
            logger.error(f"Error updating metrics: {e}")


In [37]:
pattern = r"(?m)\d{1,2}/\d{1,2}/\d{2,4},\s+\d{1,2}:\d{2}\s*(?:AM|PM|am|pm)\s*-\s"

In [39]:
messages = re.split(pattern, data)[1:]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.\n',
 'Deepanshu: Tera wifi sahi hua\n',
 'Hariom Nagar: nahi par vo anil ko bola hai to 10 din ki bol raha hai\n',
 'Deepanshu: Last semester se bol raha hai yeh toh\n',
 'Hariom Nagar: hnn abhi grp me num aaya hai uspe call krke boluga\n',
 'Deepanshu: Bol bhai\n',
 'Hariom Nagar: hnn\n',
 'Hariom Nagar: clg kab aa raha hai\n',
 'Deepanshu: Monday ko\n',
 'Deepanshu: Kya hua ?\n',
 'Hariom Nagar: kich nahi bas aesi.\n',
 'Deepanshu: Monday shaym tak aa jau ga\n',
 'Hariom Nagar: TAP ka form bhara hai tune\n',
 'Deepanshu: Nahi\n',
 'Deepanshu: Tune?\n',
 'Hariom Nagar: na\n',
 'Hariom Nagar: kyu nahi bhara?\n',
 'Deepanshu: Kuch fayda nahi hai\n',
 'Deepanshu: Mene discuss Kiya abhi jo member hai unke sath\n',
 'Hariom Nagar: bharat to placmet hone ke chanse bad jate\n',
 'Deepanshu: Nahi same haal hai andar ka bhi\n',
 'Deepanshu: GitHub https://share.google/8kwdTYzHQBxgy65Tw\n',
 'Hariom Nagar: class aa ja, lab hai aaj\n',
 'Deepanshu: Bsdk bus mei hu mai\n',
 'Deepanshu: Tu class aa ja\n',
 'Hariom Nagar: mess chalte hai lift me aaja\n',
 'Hariom Nagar: \n',
 'Deepanshu: Proxy mar de\n',
 'Deepanshu: Bhai plz\n',
 'Hariom Nagar: apni dono ke Roll num to side by side hai kaise bro\n',
 'Deepanshu: Kisi aas pas wale se bol de\n',
 'Hariom Nagar: thi hai me aagman ko bolta hu\n',
 'Hariom Nagar: reg form chaiye kya?\n',
 'Deepanshu: nahi hai mere pass\n',
 'Hariom Nagar: class jayga aaj\n',
 'Deepanshu: Nahi\n',

In [40]:
dates = re.findall(pattern, data)
dates

['15/08/2025, 9:56\u202fam - ',
 '21/08/2025, 1:38\u202fpm - ',
 '21/08/2025, 1:52\u202fpm - ',
 '21/08/2025, 1:52\u202fpm - ',
 '21/08/2025, 1:52\u202fpm - ',
 '21/08/2025, 1:53\u202fpm - ',
 '21/08/2025, 1:53\u202fpm - ',
 '22/08/2025, 4:29\u202fpm - ',
 '22/08/2025, 4:29\u202fpm - ',
 '22/08/2025, 4:29\u202fpm - ',
 '22/08/2025, 4:30\u202fpm - ',
 '22/08/2025, 4:30\u202fpm - ',
 '24/08/2025, 11:30\u202fam - ',
 '24/08/2025, 11:30\u202fam - ',
 '24/08/2025, 11:30\u202fam - ',
 '24/08/2025, 11:30\u202fam - ',
 '24/08/2025, 11:31\u202fam - ',
 '24/08/2025, 11:31\u202fam - ',
 '24/08/2025, 11:31\u202fam - ',
 '24/08/2025, 11:31\u202fam - ',
 '24/08/2025, 11:32\u202fam - ',
 '25/08/2025, 7:52\u202fpm - ',
 '26/08/2025, 8:35\u202fam - ',
 '26/08/2025, 8:41\u202fam - ',
 '26/08/2025, 8:41\u202fam - ',
 '26/08/2025, 5:28\u202fpm - ',
 '26/08/2025, 11:20\u202fpm - ',
 '27/08/2025, 10:00\u202fam - ',
 '27/08/2025, 10:00\u202fam - ',
 '27/08/2025, 10:01\u202fam - ',
 '27/08/2025, 10:01\u202fam - ',
 '27/08/2025, 10:02\u202fam - ',
 '28/08/2025, 6:55\u202fpm - ',
 '28/08/2025, 6:55\u202fpm - ',
 '29/08/2025, 8:35\u202fam - ',
 '29/08/2025, 8:44\u202fam - ',
 '29/08/2025, 10:48\u202fpm - ',
 '29/08/2025, 10:49\u202fpm - ',
 '29/08/2025, 10:52\u202fpm - ',
 '29/08/2025, 11:11\u202fpm - ',
 '29/08/2025, 11:31\u202fpm - ',
 '29/08/2025, 11:34\u202fpm - ',
 '29/08/2025, 11:37\u202fpm - ',
 '29/08/2025, 11:39\u202fpm - ',
 '29/08/2025, 11:45\u202fpm - ',
 '29/08/2025, 11:47\u202fpm - ',
 '29/08/2025, 11:48\u202fpm - ',
 '29/08/2025, 11:50\u202fpm - ',
 '29/08/2025, 11:51\u202fpm - ',
 '01/09/2025, 9:21\u202fpm - ',
 '01/09/2025, 9:23\u202fpm - ',
 '01/09/2025, 9:41\u202fpm - ',
 '03/09/2025, 1:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '07/09/2025, 10:23\u202fpm - ',
 '09/09/2025, 8:47\u202fam - ',
 '11/09/2025, 11:37\u202fam - ',
 '12/09/2025, 12:59\u202fpm - ',
 '12/09/2025, 12:59\u202fpm - ',
 '12/09/2025, 1:00\u202fpm - ',
 '12/09/2025, 1:00\u202fpm - ',
 '13/09/2025, 8:46\u202fam - ',
 '13/09/2025, 8:46\u202fam - ',
 '14/09/2025, 8:31\u202fpm - ',
 '14/09/2025, 9:22\u202fpm - ',
 '16/09/2025, 9:48\u202fpm - ',
 '16/09/2025, 9:48\u202fpm - ',
 '16/09/2025, 9:48\u202fpm - ',
 '16/09/2025, 9:49\u202fpm - ',
 '16/09/2025, 9:49\u202fpm - ',
 '16/09/2025, 9:49\u202fpm - ',
 '16/09/2025, 9:51\u202fpm - ',
 '16/09/2025, 10:41\u202fpm - ',
 '16/09/2025, 10:41\u202fpm - ',
 '16/09/2025, 10:41\u202fpm - ',
 '16/09/2025, 10:42\u202fpm - ',
 '16/09/2025, 11:22\u202fpm - ',
 '16/09/2025, 11:22\u202fpm - ',
 '16/09/2025, 11:22\u202fpm - ',
 '16/09/2025, 11:31\u202fpm - ',
 '23/09/2025, 8:12\u202fam - ',
 '23/09/2025, 9:25\u202fam - ',
 '23/09/2025, 9:26\u202fam - ']

In [42]:
df = pd.DataFrame({'user_message': messages, 'message_date': dates})
# convert message_date type
df['message_date'] = pd.to_datetime(df['message_date'], format='%d/%m/%Y, %I:%M %p - ')

df.rename(columns={'message_date': 'date'}, inplace=True)

df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-08-15 09:56:00
1                    Deepanshu: Tera wifi sahi hua\n 2025-08-21 13:38:00
2  Hariom Nagar: nahi par vo anil ko bola hai to ... 2025-08-21 13:52:00
3  Deepanshu: Last semester se bol raha hai yeh t... 2025-08-21 13:52:00
4  Hariom Nagar: hnn abhi grp me num aaya hai usp... 2025-08-21 13:52:00

In [44]:
df.shape

(91, 3)

In [43]:
# seperate user and message
users = []
messages = []
for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

df.head()

,date,user,message
0,2025-08-15 09:56:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2025-08-21 13:38:00,Deepanshu,Tera wifi sahi hua\n
2,2025-08-21 13:52:00,Hariom Nagar,nahi par vo anil ko bola hai to 10 din ki bol ...
3,2025-08-21 13:52:00,Deepanshu,Last semester se bol raha hai yeh toh\n
4,2025-08-21 13:52:00,Hariom Nagar,hnn abhi grp me num aaya hai uspe call krke bo...

In [45]:
df['year']  = df['date'].dt.year

In [46]:
df['month'] =df['date'].dt.month_name()

In [47]:
df['day'] = df['date'].dt.day

In [48]:
df['hour'] = df['date'].dt.hour

In [49]:
df['minute'] = df['date'].dt.minute

In [50]:
df.head()

,date,user,message,year,month,day,hour,minute
0,2025-08-15 09:56:00,group_notification,Messages and calls are end-to-end encrypted. O...,2025,August,15,9,56
1,2025-08-21 13:38:00,Deepanshu,Tera wifi sahi hua\n,2025,August,21,13,38
2,2025-08-21 13:52:00,Hariom Nagar,nahi par vo anil ko bola hai to 10 din ki bol ...,2025,August,21,13,52
3,2025-08-21 13:52:00,Deepanshu,Last semester se bol raha hai yeh toh\n,2025,August,21,13,52
4,2025-08-21 13:52:00,Hariom Nagar,hnn abhi grp me num aaya hai uspe call krke bo...,2025,August,21,13,52